<a href="https://colab.research.google.com/github/Anupampal1992/Group-Project/blob/main/Traffic_Accident.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!git clone  https://github.com/Anupampal1992/Group-Project.git
%cd Group-Project
!ls

Cloning into 'Group-Project'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), 178.98 KiB | 10.53 MiB/s, done.
/content/Group-Project/Group-Project/Group-Project
'Traffic Accident Severity Predictor Dataset.csv'

In [14]:
import pandas as pd
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [13]:

df = pd.read_csv('Traffic Accident Severity Predictor Dataset.csv')
df.head()

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition,Accident
0,Rainy,City Road,Morning,1.0,100.0,5.0,0.0,NaN,Wet,Car,51.0,48.0,Artificial Light,0
1,Clear,Rural Road,Night,NaN,120.0,3.0,0.0,Moderate,Wet,Truck,49.0,43.0,Artificial Light,0
2,Rainy,Highway,Evening,1.0,60.0,4.0,0.0,Low,Icy,Car,54.0,52.0,Artificial Light,0
3,Clear,City Road,Afternoon,2.0,60.0,3.0,0.0,Low,Under Construction,Bus,34.0,31.0,Daylight,0
4,Rainy,Highway,Morning,1.0,195.0,11.0,0.0,Low,Dry,Car,62.0,55.0,Artificial Light,1

In [16]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
/content/Group-Project/Group-Project/Group-Project

In [17]:
!pwd

/content/Group-Project/Group-Project/Group-Project

In [18]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [19]:
df.describe()

,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Driver_Age,Driver_Experience,Accident
count,19958.000000,19958.000000,19958.000000,19958.000000,19958.000000,19958.000000,20000.000000
mean,1.010923,71.448943,3.282694,0.164445,43.146758,38.859154,0.292000
std,0.783966,32.366260,1.999111,0.370688,15.099349,15.249536,0.454694
min,0.000000,30.000000,1.000000,0.000000,18.000000,9.000000,0.000000
25%,0.000000,50.000000,2.000000,0.000000,30.000000,26.000000,0.000000
50%,1.000000,60.000000,3.000000,0.000000,43.000000,39.000000,0.000000
75%,2.000000,80.000000,4.000000,0.000000,56.000000,52.000000,1.000000
max,2.000000,213.000000,14.000000,1.000000,69.000000,69.000000,1.000000